"""
envs/language_table_env.py
──────────────────────────
Google Language Table (2D language-conditioned block pushing) simulation wrapper.

Provides:
  LanguageTableAgent — receding-horizon VLA controller.  Predicts a chunk of 2D
                       ee-delta setpoints; the stored/predicted action IS the env
                       step space, so it denormalises and commands DIRECTLY — no
                       integration, no drift (mirrors AlohaAgent, NOT PushTAgent).
                       The current episode's instruction string is fed to the VLM
                       (Language Table is language-conditioned: command per episode).
  make_lt_env()      — constructs the PyBullet sim with a chosen reward_factory:
                         in-dist  → "block2block"
                         OOD      → "separate" / "point"  (verbs held out of training)
  run_episode()      — runs one episode under the gym 0.23 API (obs-only reset,
                       4-tuple step), success = (reward > 0).

NB: requires the TF stub (envs/lt_compat) installed BEFORE importing language_table.
This module is imported lazily by evaluate.py only for the language_table dataset,
so it never affects pusht/aloha runs.
"""

from __future__ import annotations

import time
from pathlib import Path

import numpy as np
import torch
from PIL import Image, ImageDraw

from data.language_table import resize_frame
from envs.lt_compat import install_tf_stub

install_tf_stub()  # must precede any language_table import
from language_table.environments import blocks
from language_table.environments import language_table as lt_mod
from language_table.environments.rewards import block2block
from language_table.environments.rewards import separate_blocks
from language_table.environments.rewards import point2block
from language_table.environments.rewards import block2absolutelocation


# ── Reward factories: which command type the live sim generates ────────────────
REWARD_FACTORIES = {
    "block2block":    block2block.BlockToBlockReward,             # in-distribution
    "block2absolute": block2absolutelocation.BlockToAbsoluteLocationReward,  # in-dist
    "separate":       separate_blocks.SeparateBlocksReward,       # OOD (held out)
    "point":          point2block.PointToBlockReward,             # OOD (held out)
}
# class names vary across versions — add the remaining task families if present.
for _mod, _names, _key in [
    ("block2relativelocation", ("BlockToRelativeLocationReward", "Block2RelativeLocationReward"), "block2relative"),
    ("block2block_relative_location", ("BlockToBlockRelativeLocationReward",), "between"),
    ("block1_to_corner", ("Block1ToCornerLocationReward", "Block1ToCornerReward"), "corner"),
]:
    try:
        _m = __import__("language_table.environments.rewards." + _mod, fromlist=[_mod])
        for _n in _names:
            if hasattr(_m, _n):
                REWARD_FACTORIES[_key] = getattr(_m, _n)
                break
    except Exception:
        pass


def make_lt_env(reward_name: str = "block2block", seed: int = 0):
    """Construct a Language Table env whose instructions are generated by the named
    reward factory.  BLOCK_8 = the 8-block variant used across language_table_sim."""
    if reward_name not in REWARD_FACTORIES:
        raise ValueError(f"Unknown reward {reward_name!r}. "
                         f"Available: {sorted(REWARD_FACTORIES)}")
    return lt_mod.LanguageTable(
        block_mode=blocks.LanguageTableBlockVariants.BLOCK_8,
        reward_factory=REWARD_FACTORIES[reward_name],
        seed=seed,
    )


def get_instruction(env, obs) -> str:
    """Recover the current episode's instruction string from the env (preferred) or
    by byte-decoding the tokenised obs['instruction'] (fallback)."""
    v = getattr(env, "_instruction_str", None)
    if isinstance(v, str) and v.strip():
        return v.strip()
    arr = np.asarray(obs.get("instruction", []) if isinstance(obs, dict) else [])
    nz = arr[arr != 0]
    if nz.size:
        try:
            return bytes(nz.astype(np.uint8)).decode("utf-8", errors="ignore").strip()
        except Exception:
            pass
    return ""


class LanguageTableAgent:
    """Receding-horizon VLA agent for Language Table. Re-plans every inference_horizon
    steps; conditions the VLM on the CURRENT episode instruction string."""

    def __init__(self, vlm, train_model, cfg, device) -> None:
        self.vlm         = vlm
        self.train_model = train_model
        self.cfg         = cfg
        self.device      = device

        self.action_mean = np.array(cfg.action_mean, dtype=np.float32)
        self.action_std  = np.array(cfg.action_std,  dtype=np.float32)
        self.state_mean  = np.array(cfg.state_mean,  dtype=np.float32)
        self.state_std   = np.array(cfg.state_std,   dtype=np.float32)

        self.instruction = cfg.task_text     # set per-episode by run_episode
        self._buffer: list[np.ndarray] = []
        self.replan_count = 0

    def reset(self) -> None:
        self._buffer = []
        self.replan_count = 0

    def _norm_state(self, s: np.ndarray) -> np.ndarray:
        return (s - self.state_mean) / (self.state_std + 1e-8)

    def _denorm_action(self, a: np.ndarray) -> np.ndarray:
        return a * self.action_std + self.action_mean

    @torch.no_grad()
    def _replan(self, image: Image.Image, state: np.ndarray) -> None:
        state_t = torch.from_numpy(
            self._norm_state(state).astype(np.float32)
        ).unsqueeze(0).to(self.device)

        inputs           = self.vlm.build_vlm_inputs([image], [self.instruction], self.device)
        tokens, img_mask = self.vlm.encode_vlm(inputs)

        acts_flat = self.train_model.sample(
            tokens, state_t, num_steps=self.cfg.num_flow_steps, img_mask=img_mask
        )
        acts = acts_flat.view(
            self.cfg.action_horizon, self.cfg.action_dim
        ).cpu().float().numpy()

        acts = acts[: self.cfg.inference_horizon]
        # Predicted action == env-step 2D delta — denormalise, command directly.
        self._buffer       = [self._denorm_action(a).astype(np.float32) for a in acts]
        self.replan_count += 1

    def act(self, image: Image.Image, state: np.ndarray) -> np.ndarray:
        if not self._buffer:
            self._replan(image, state)
        return self._buffer.pop(0)


def annotate_frame(rgb, ep, total_eps, step, max_steps, reward, success, instruction):
    """Draw a small HUD (instruction + progress) onto an observation frame."""
    img  = Image.fromarray(np.ascontiguousarray(rgb).astype(np.uint8)).convert("RGB")
    W, H = img.size
    scale = max(1, W // 320)
    img = img.resize((W * 2, H * 2))           # upscale a bit so text is legible
    draw = ImageDraw.Draw(img)
    bar = Image.new("RGBA", (img.size[0], 46), (0, 0, 0, 170))
    img.paste(bar, (0, 0), bar)
    draw = ImageDraw.Draw(img)
    col = (50, 220, 50) if success else (255, 255, 255)
    draw.text((6, 4),  f"Ep {ep+1}/{total_eps}  step {step}/{max_steps}", fill=col)
    draw.text((6, 20), (instruction or "")[:60], fill=(220, 220, 120))
    if success:
        draw.text((img.size[0] // 2 - 40, img.size[1] // 2), "SUCCESS", fill=(50, 220, 50))
    return np.array(img.convert("RGB"))


def run_episode(env, agent, cfg, ep_idx, total_eps, save_video, video_dir,
                require_substring=None, max_reset_tries=80):
    """Run one Language Table episode (gym 0.23 API). Returns a result dict.

    success = the sparse task reward goes positive; max_coverage mirrors success as a
    0/1 task-progress fraction so the generic evaluate.py summary reads correctly.

    require_substring: if set, the env is reset until the generated instruction
    CONTAINS this token (case-insensitive).  Used to restrict OOD evaluation to
    instructions that actually use a held-out verb ('separate'/'point') — the same
    reward factory also emits alternate phrasings ('move X away from Y') that overlap
    the training distribution, which we must exclude for a clean new-command test.
    """
    out = env.reset()
    obs = out[0] if isinstance(out, tuple) else out
    instruction = get_instruction(env, obs)
    if require_substring:
        tries = 0
        while require_substring.lower() not in instruction.lower() and tries < max_reset_tries:
            out = env.reset()
            obs = out[0] if isinstance(out, tuple) else out
            instruction = get_instruction(env, obs)
            tries += 1
    agent.reset()
    agent.instruction = instruction

    frames, max_reward, success, reward = [], 0.0, False, 0.0
    t0 = time.time()
    step = 0
    for step in range(cfg.sim_max_steps):
        rgb    = np.asarray(obs["rgb"])
        image  = resize_frame(rgb, cfg.lt_img_w, cfg.lt_img_h)
        state  = np.asarray(obs["effector_translation"], dtype=np.float32)
        action = agent.act(image, state)
        action = np.clip(action, -0.1, 0.1).astype(np.float32)

        sout = env.step(action)
        if len(sout) == 5:                       # gymnasium 5-tuple (defensive)
            obs, reward, term, trunc, info = sout
            done = bool(term or trunc)
        else:                                    # gym 0.23 4-tuple (expected)
            obs, reward, done, info = sout
        reward     = float(reward)
        max_reward = max(max_reward, reward)
        if reward > 0:
            success = True

        if save_video:
            frames.append(annotate_frame(rgb, ep_idx, total_eps, step + 1,
                                         cfg.sim_max_steps, reward, success, instruction))
        if done or success:
            break

    if save_video and frames:
        try:
            import imageio
            imageio.mimsave(str(Path(video_dir) / f"episode_{ep_idx+1:02d}.mp4"),
                            frames, fps=cfg.video_fps)
        except Exception as e:
            print(f"    [warn] video save: {e}")

    elapsed = time.time() - t0
    tag = "SUCCESS" if success else "failed "
    print(f"  Ep {ep_idx+1:2d}/{total_eps} | {tag} | reward={max_reward:.2f} | "
          f"steps={step+1} | replans={agent.replan_count} | {elapsed:.0f}s | {instruction[:50]!r}")
    return {
        "episode": ep_idx + 1,
        "steps": step + 1,
        "max_reward": round(max_reward, 4),
        "final_reward": round(reward, 4),
        "max_coverage": 1.0 if success else 0.0,
        "is_success": success,
        "instruction": instruction,
        "replan_count": agent.replan_count,
        "elapsed_sec": round(elapsed, 1),
    }
