"""Generate tables.md from the current analysis outputs.

Kept as a script rather than hand-written tables so the numbers in the write-up
cannot drift from the numbers in the analysis.

Design rules, all of which exist because an earlier version broke them:

1. NO literal model list, dataset list, or read depth. Everything comes from
   `backbones` (ARMS / KEYS / GATE_KEYS / DOC_LAYER / PAIRS). Six separate files
   used to keep private copies of the roster, which is how a figure came to plot
   seven curves under a nine-curve caption.

2. NO `d100`. Every per-arm number is read at the arm's DOCUMENTED layer -- the
   `doc` tap. Reading each arm at its own last layer compares SmolVLA's layer 16
   against SmolVLM2's layer 32 and GR00T's 16 against Cosmos's 28, which is the
   confound that retracted this study's original finding 3.

3. Every table states its provenance. The header records the mtime of each
   source JSON, so a stale table is visible rather than inferred.

4. The frozen pair is reported as a NULL CONTROL, not as a result. SmolVLA's VLM
   is 345/345 tensors identical to stock SmolVLM2's, so read at the same layer
   the two must agree exactly. Whatever they differ by is this method's noise
   floor, and every other paired effect is sized against it.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from backbones import ARMS, DOC_LAYER, GATE_KEYS, KEYS, PAIRS  # noqa: E402

ROOT = HERE.parents[2]
DIR = ROOT / "asset" / "analysis" / "latent_compare"

NAME = {
    "qwen": "Qwen3.5-0.8B", "pi05": "Pi-0.5", "paligemma": "PaliGemma-3B",
    "smolvla": "SmolVLA", "smolvlm2": "SmolVLM2-500M", "groot": "GR00T N1.7-3B",
    "cosmos": "Cosmos-Reason2-2B", "qwen3vl": "Qwen3-VL-2B",
}
ROLE = {
    "qwen": "frozen, ours", "pi05": "robot-FT", "paligemma": "stock control",
    "smolvla": "VLM frozen", "smolvlm2": "stock control", "groot": "robot-FT",
    "cosmos": "physical-AI FT", "qwen3vl": "stock control",
}
KEY_LABEL = {
    "aloha_transfer": "ALOHA transfer-cube", "aloha_insertion": "ALOHA insertion",
    "libero_goal": "LIBERO-Goal", "language_table": "Language Table (curated)",
}
DEPTH_TAGS = ["d000", "d025", "d050", "d075", "d100"]
DEPTH_HEAD = ["0%", "25%", "50%", "75%", "100%"]
NULL_PAIR = ("smolvla", "smolvlm2")


def f(v, nd: int = 3) -> str:
    return "--" if v is None else f"{v:.{nd}f}"


def load(name: str) -> tuple[dict, str]:
    p = DIR / name
    stamp = datetime.fromtimestamp(p.stat().st_mtime).strftime("%Y-%m-%d %H:%M")
    return json.loads(p.read_text(encoding="utf-8")), stamp


def main() -> int:
    M, t_m = load("metrics.json")
    J, t_j = load("joint_metrics.json")
    T, t_g = load("task_geometry.json")
    D, t_d = load("depth_sweep.json")

    o: list[str] = []
    a = o.append

    a("# Latent comparison — tables\n")
    a("Generated by `scripts/analysis/latent_compare/report.py`. Do not edit by hand.\n")
    a("**Every per-arm number below is read at that arm's documented layer** "
      "(the `doc` tap), not at its own last layer — see Table 1. Reading each arm "
      "at its final layer compares different depths across a pair and measures "
      "read depth rather than weights.\n")
    a("| source | last written |")
    a("|---|---|")
    for n, t in [("metrics.json", t_m), ("joint_metrics.json", t_j),
                 ("task_geometry.json", t_g), ("depth_sweep.json", t_d)]:
        a(f"| `{n}` | {t} |")
    a("")

    # ── Table 1: provenance of the read layer ────────────────────────────────
    a("## Table 1 — What is measured, and where\n")
    a("Sourced from each model's shipped config, not from paper text. `KV` means "
      "the policy's action expert attends to per-layer keys and values rather "
      "than to a single hidden state, so a second tap is extracted for it.\n")
    a("| Arm | Role | Reads layer | of | Tensor | Source |")
    a("|---|---|---|---|---|---|")
    for m in ARMS:
        layer, n_layers, mode, prov = DOC_LAYER[m]
        tensor = "KV, all layers" if mode == "kv" else "hidden state"
        a(f"| {NAME[m]} | {ROLE[m]} | {layer} | {n_layers} | {tensor} | {prov} |")
    a("\nPooling: mean over tokens within each role mask (image / text / all), "
      "attention-masked so padding never enters the average.\n")

    # ── Table 2: headline probe results ──────────────────────────────────────
    a("## Table 2 — Probe results at the documented layer (all-token pool)\n")
    a("| Dataset | Arm | k | action R² | state R² | phase R² |")
    a("|---|---|---|---|---|---|")
    for k in KEYS:
        for m in ARMS:
            r = M.get(k, {}).get(m)
            if not r:
                continue
            fa = r["factors"]["all"]
            dim = r["dimensionality"].get("doc_all", {})
            a(f"| {KEY_LABEL[k]} | {NAME[m]} | {dim.get('n_retained', '--')} | "
              f"{f(fa['r2_action'])} | {f(fa['r2_state'])} | {f(fa['r2_phase'])} |")
    a("")

    # ── Table 3: the language test ───────────────────────────────────────────
    a("## Table 3 — Instruction encoding on LIBERO-Goal\n")
    a("Ten goals share one fixed scene and object set, so an **image** token can "
      "only carry goal identity if instruction information was propagated into "
      "it. The text column is the sanity check and passes everywhere.\n")
    a("| Arm | image-token η² | text-token η² | action R² (image) |")
    a("|---|---|---|---|")
    for m in ARMS:
        r = M.get("libero_goal", {}).get(m)
        if not r:
            continue
        fi, ft = r["factors"]["image"], r["factors"]["text"]
        a(f"| {NAME[m]} | {f(fi['eta2_instruction'])} | {f(ft['eta2_instruction'])} | "
          f"{f(fi['r2_action'])} |")
    a("")

    # ── Table 3b: instruction encoding split by episode phase ────────────────
    ps_path = DIR / "phase_split_libero.json"
    if ps_path.exists():
        P = json.loads(ps_path.read_text(encoding="utf-8"))
        stamp = datetime.fromtimestamp(ps_path.stat().st_mtime).strftime("%Y-%m-%d %H:%M")
        a("## Table 3b — Instruction encoding vs episode phase (LIBERO-Goal, image tokens)\n")
        a("All ten tasks share one scene, and initial object positions jitter "
          "independently of task — so at the start of an episode the frame carries "
          "essentially no task information. High η² there can only come from the "
          "instruction; a rising curve is the goal being inferred from the "
          "unfolding trajectory. The null is permuted at **episode** level, since "
          "frames within an episode share a task.\n")
        a(f"_Source: `phase_split_libero.json`, {stamp}._\n")
        a("| Arm | early (<0.10) | mid | late (>0.90) | null p95 | early excess |")
        a("|---|---|---|---|---|---|")
        for m in ARMS:
            r = P.get(m)
            if not r:
                continue
            a(f"| {NAME[m]} | {f(r['early'])} | {f(r['mid'])} | {f(r['late'])} | "
              f"{f(r['null_p95'])} | **{r['excess_early']:+.3f}** |")
        a("\nPi-0.5 is flat across the episode — it resolves the goal at frame 0, before "
          "any visual evidence exists. Every other arm rises from the noise floor. "
          "Pooling across phase (Table 3) hides this: episode progress enters the "
          "denominator and compresses every arm toward a similar value.\n")

    # ── Table 3c: can image tokens see the instruction at all? ───────────────
    tv_path = DIR / "text_visibility_libero.json"
    if tv_path.exists():
        V = json.loads(tv_path.read_text(encoding="utf-8"))
        stamp = datetime.fromtimestamp(tv_path.stat().st_mtime).strftime("%Y-%m-%d %H:%M")
        a("## Table 3c — Do image tokens see the instruction?\n")
        a("Same frames, different text; the number is how far the image-token "
          "vector moves, relative to its own norm. All conditions are encoded in "
          "one batch so padding length is identical — otherwise a changed token "
          "count alone perturbs a bfloat16 vector by ~1e-3.\n")
        a(f"_Source: `text_visibility_libero.json`, {stamp}._\n")
        a("| Arm | different instruction | same words, scrambled | empty text | ratio | reading |")
        a("|---|---|---|---|---|---|")
        for m in ARMS:
            r = V.get(m)
            if not r:
                continue
            ratio = r.get("ratio_meaning_vs_scrambled")
            a(f"| {NAME[m]} | **{f(r['diff_instruction'], 4)}** | "
              f"{f(r['scrambled'], 4)} | {f(r['empty'], 4)} | "
              f"{'--' if ratio is None else f'{ratio:.2f}'} | {r['reading']} |")
        a("\n**Exactly zero means bit-identical**, not merely small: those arms produce "
          "image tokens before the instruction is attended to, so no amount of training "
          "could make them carry it. A non-zero value that is the *same* for a changed "
          "meaning and for shuffled words is token-level reactivity, not language "
          "understanding — only a ratio above 1 indicates the representation tracks "
          "what the sentence means.\n")

    # ── Table 4: paired deltas, with the null control ────────────────────────
    a("## Table 4 — Paired deltas (finetuned − its own base)\n")
    a("Each pair is verified by direct tensor comparison, and both arms are read "
      "at the same absolute layer, so only the weights differ.\n")
    a("| Pair | Δ task/scene | RSA to base | Δ η² instruction (image) |")
    a("|---|---|---|---|")
    rsa_models = J["rsa"].get("models", ARMS)
    R = J["rsa"]["matrix"]
    for ft_, st in PAIRS:
        dr = (J["per_model"]["image"][ft_]["task_scene_ratio"]
              - J["per_model"]["image"][st]["task_scene_ratio"])
        rsa = R[rsa_models.index(ft_)][rsa_models.index(st)]
        de = (M["libero_goal"][ft_]["factors"]["image"]["eta2_instruction"]
              - M["libero_goal"][st]["factors"]["image"]["eta2_instruction"])
        note = "  ← **null control**" if (ft_, st) == NULL_PAIR else ""
        a(f"| {NAME[ft_]} ← {NAME[st]} | {dr:+.4f} | {f(rsa, 4)} | {de:+.4f}{note} |")
    a(f"\n**Reading this table.** {NAME[NULL_PAIR[0]]}'s VLM is 345 of 345 tensors "
      f"identical to stock {NAME[NULL_PAIR[1]]} — it froze the backbone and trained "
      f"only the action expert — so read at the same layer the two *must* agree "
      f"exactly. That row is therefore a correctness check, and it fixes the noise "
      f"floor: any effect of comparable magnitude is measurement error, not signal.\n")

    # ── Table 5: task geometry ───────────────────────────────────────────────
    a("## Table 5 — Task geometry (image tokens)\n")
    a("Distances are normalised per backbone by its own mean pairwise distance, "
      "so widths cancel. With three datasets the three distances determine a "
      "triangle **exactly** — no projection, no error.\n")
    pair_names = [f"{a_}↔{b}" for i, a_ in enumerate(["AT", "AI", "LG"])
                  for b in ["AT", "AI", "LG"][i + 1:]]
    a("| Arm | " + " | ".join(pair_names) + " | task/scene ratio |")
    a("|---|" + "---|" * (len(pair_names) + 1))
    for m in ARMS:
        Dn = T[m]["dist_norm"]
        cells = [f(Dn[i][j], 2) for i in range(len(KEYS))
                 for j in range(i + 1, len(KEYS))]
        ratio = J["per_model"]["image"][m]["task_scene_ratio"]
        a(f"| {NAME[m]} | " + " | ".join(cells) + f" | **{f(ratio)}** |")
    a("\nAT = ALOHA transfer-cube, AI = ALOHA insertion, LG = LIBERO-Goal. "
      "Higher ratio = organised by task rather than by scene appearance.\n")

    # ── Table 6: RSA ─────────────────────────────────────────────────────────
    a("## Table 6 — Representational similarity between backbones\n")
    a("Spearman correlation of frame×frame distance matrices — the one comparison "
      "that works across models of different width.\n")
    a("| | " + " | ".join(NAME[m] for m in rsa_models) + " |")
    a("|---|" + "---|" * len(rsa_models))
    for i, m in enumerate(rsa_models):
        a(f"| **{NAME[m]}** | " + " | ".join(f(R[i][j], 3) for j in range(len(rsa_models))) + " |")
    a("")

    # ── Table 7: depth sweep ─────────────────────────────────────────────────
    a("## Table 7 — Action decodability vs read depth (all-token pool)\n")
    a("**0%** is the vision tower output through the multimodal projector merged "
      "with the text embedding lookup, *before any decoder block runs*. `doc` is "
      "the arm's documented read layer, which for most arms is not a grid point.\n")
    a("| Dataset | Arm | " + " | ".join(DEPTH_HEAD) + " | doc | best | gain vs last |")
    a("|---|---|" + "---|" * (len(DEPTH_HEAD) + 3))
    for k in KEYS:
        for m in ARMS:
            rows = D.get(k, {}).get(m)
            if not rows:
                continue
            cells = [f(rows.get(t, {}).get("r2_action")) for t in DEPTH_TAGS]
            s = rows.get("_summary", {})
            doc = f(rows.get("doc", {}).get("r2_action"))
            best = s.get("best_depth", "--")
            gain = s.get("gain_over_last")
            a(f"| {KEY_LABEL[k]} | {NAME[m]} | " + " | ".join(cells)
              + f" | {doc} | **{best}** | {'--' if gain is None else f'{gain:+.3f}'} |")
    a("")

    # ── Table 8: KV vs hidden ────────────────────────────────────────────────
    a("## Table 8 — What the action expert actually reads (KV arms only)\n")
    a("For Pi-0.5 and SmolVLA the expert attends to per-layer keys and values, "
      "not to the residual stream. Per layer K = W_k·h is a *linear* map of the "
      "hidden state, so a linear probe on K cannot beat one on h; across layers "
      "the concatenation is bounded by no single hidden state and can exceed all "
      "of them.\n")
    a("| Dataset | Arm | doc (hidden) | kv | Δ | k doc | k kv | raw dim kv |")
    a("|---|---|---|---|---|---|---|---|")
    any_kv = False
    for k in KEYS:
        for m in ARMS:
            rows = D.get(k, {}).get(m, {})
            if "kv" not in rows:
                continue
            any_kv = True
            d, kv = rows["doc"], rows["kv"]
            a(f"| {KEY_LABEL[k]} | {NAME[m]} | {f(d['r2_action'])} | "
              f"{f(kv['r2_action'])} | {kv['r2_action'] - d['r2_action']:+.3f} | "
              f"{d['n_retained']} | {kv['n_retained']} | {kv.get('raw_dim', '--')} |")
    if not any_kv:
        a("| _no KV taps found_ | | | | | | | |")
    a("\n**Caveat.** The KV taps retain roughly twice the components of the hidden "
      "taps, so this is a comparison at each tap's own retained dimensionality, "
      "not a PC-matched one. Parallel analysis places those components above the "
      "permutation null and the R² is 5-fold cross-validated, so it is not "
      "overfitting — but it is a capacity difference, and a matched-k test has "
      "not been run.\n")

    # ── Table 9: the dataset gate ────────────────────────────────────────────
    a("## Table 9 — Dataset gate\n")
    a("*Is the action linearly recoverable from one observation, by any encoder?* "
      "**Language Table appears here and nowhere else in this file**: it fails the "
      "gate, and a gate needs a documented negative to be a scale rather than two "
      "points.\n")
    a("| Dataset | action R² range | verdict |")
    a("|---|---|---|")
    for k in GATE_KEYS:
        vals = [M[k][m]["factors"]["all"]["r2_action"] for m in ARMS if m in M.get(k, {})]
        if not vals:
            continue
        verdict = ("**fails the gate** — excluded from every other table"
                   if max(vals) < 0.10 else "usable")
        a(f"| {KEY_LABEL[k]} | {f(min(vals))} – {f(max(vals))} | {verdict} |")
    a("\nThe spread *within* a dataset is far smaller than the gap *between* "
      "datasets, across eight backbones spanning three families and 0.5B–3B "
      "parameters — which is what makes decodability a property of the data "
      "rather than of any backbone.\n")

    text = "\n".join(o) + "\n"
    out_path = DIR / "tables.md"
    out_path.write_text(text, encoding="utf-8")
    # The Thai (cp874) console cannot encode the superscripts and arrows used
    # above; write the file first, then print defensively so a console
    # limitation can never fail the run.
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    print(f"wrote {out_path}  ({len(text):,} chars, {len(o)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
